feat: add typescript support using deno runtime
codecrafters-io/build-your-own-http-server pull request #41
Opened 2024-04-18 11:33 UTC by ryan-gang

2024-04-18 11:38 UTC, ryan-gang commented
Implemented the starter using `Deno.serve` initially. (https://deno.land/api@v1.42.4?s=Deno.serve)
But it kept on failing our anti-cheat. 
Turns out the server automatically adds the `date` header, which we check in the anti-cheat stage.

Wanted to document it for later.

2024-04-23 12:34 UTC, rohitpaulk requested changes
Added notes in the Git PR, dockerfile shouldn't be using app code

2024-04-25 19:34 UTC, rohitpaulk commented on compiled_starters/typescript/app/main.ts
> +// You can use print statements as follows for debugging, they'll be visible when running tests.
Let's move this to just above the "// uncomment this" block (it's more likely to get noticed that way + the diff looks cleaner)

2024-04-25 19:35 UTC, rohitpaulk commented on course-definition.yml
> +    release_status: "beta"
Would recommend doing `alpha` first and trying this out btw - at least for the first challenge that we deploy that uses Bun. After that it's okay to do beta directly if you're confident

2024-04-25 19:35 UTC, rohitpaulk commented on solutions/typescript/01-connect-to-port/code/codecrafters.yml
> +# Available versions: deno-1.42
```suggestion
# Available versions: bun-1.1
```

2024-04-25 19:36 UTC, rohitpaulk commented on starter_templates/codecrafters.yml
> +# Available versions: deno-1.42
```suggestion
# Available versions: bun-1.1
```

2024-04-26 09:18 UTC, ryan-gang commented on course-definition.yml
> +    release_status: "beta"
Will deploy git first, and test with that. 
Only git would be alpha, all others I have set to beta.

2024-04-26 09:23 UTC, merged