Add Zig support for the HTTP challenge
codecrafters-io/build-your-own-http-server pull request #68
Opened 2024-06-03 07:47 UTC by glokta1

2024-06-03 11:31 UTC, rohitpaulk commented on compiled_starters/zig/build.zig
> +    const run_cmd = b.addRunArtifact(exe);
@glokta1 I think there are some changes required to make this accept args (which will be required in the stages related to files). Can you check and see what we're doing in other challenges?

2024-06-03 11:33 UTC, rohitpaulk commented on starter_templates/zig/README.md
> +This is a starting point for Go solutions to the
I don't think you need a separate `README.md` file - `starter_templates/README.md` should work, no?

2024-06-03 11:34 UTC, rohitpaulk commented on starter_templates/zig/codecrafters.yml
> +language_pack: zig-0.12
@glokta1 look at how other languages do this - They don't define separate `codecrafters.yml` files

2024-06-03 11:34 UTC, rohitpaulk requested changes
Notes added

2024-06-03 13:21 UTC, rohitpaulk approved these changes

2024-06-03 13:51 UTC, merged

2024-06-05 10:22 UTC, ryan-gang commented
@glokta1 `test(zig)` tests didn't trigger for this PR. 
And I feel there is some issues there. All the currently open PRs are having `test(zig)` failing. 
Can you take a look at this please ?

2024-06-05 10:57 UTC, glokta1 commented
@ryan-gang Just merged a change that should fix it https://github.com/codecrafters-io/build-your-own-http-server/pull/70.

2024-06-05 11:40 UTC, ryan-gang commented
Thanks @glokta1!