Update compression 1 instructions
codecrafters-io/build-your-own-http-server pull request #75
Opened 2024-06-10 21:33 UTC by vic-ma

2024-06-10 21:41 UTC, vic-ma commented on course-definition.yml
> +      For this stage, you don't need to compress the body. You'll implement compression in a later stage.
I moved this from the notes section to here. It solves the problem you mentioned about the tests containing the uncompressed body. I also think it's important enough to mention here instead of in notes.

I think just omitting the body from the tests doesn't solve the confusion, because the reader will still be wondering whether they need to compress the body or not. Similarly, just having it in notes is also a bit "late." So I think adding a clear statement right before the tests is best.

2024-06-10 21:42 UTC, vic-ma commented
@rohitpaulk

2024-06-11 14:41 UTC, vic-ma commented
Small fix: change `/echo/<str>` to `/echo/{str}`

2024-06-12 21:42 UTC, rohitpaulk commented on course-definition.yml
> +      For this stage, you don't need to compress the body. You'll implement compression in a later stage.
Yep, this makes sense!

2024-06-12 21:43 UTC, rohitpaulk commented on course-definition.yml
> +      abc
@vic-ma I see that the note was moved above, is it intention that we're still showing the uncompressed body here?

2024-06-12 21:44 UTC, rohitpaulk requested changes
Added a note re: uncompressed body

2024-06-12 22:37 UTC, vic-ma commented on course-definition.yml
> +      abc
@rohitpaulk Yes, I think it's better to keep it in. This makes it clear to the reader that the body is indeed uncompressed.

I think for tests, it's good to not omit anything. That way, the reader can see clearly what the expected output/behaviour is, and they can compare that to their own program.

2024-06-13 17:24 UTC, rohitpaulk commented on course-definition.yml
> +      abc
For context, our tests don't check `Content-Length` and body here - we only check for the `Content-Encoding` header. We start checking for `Content-Length` and the body only in later stages.

There are essentially three things at play here: 

1. The expected behaviour that the tester will test in this stage
2. The "intermediary" behaviour of a user's program when they've only implemented this  stage but not the next (this incorrectness WILL not be tested, since all tests need to pass for later stages too)
3. The "final" behaviour a user's program will implement, once it properly implements the spec and passes later stages

Maybe I'm overthinking this, but I'm worried that we'll cause confusion around (3) by trying to highlight (2) too much. I think we should be downplaying (2) if possible, and if we have to include it, it should always be accompanied with notes saying "yes this is incorrect, we'll handle in the next stages".

Does that make sense? I'm not opposed to keeping the full response here, but maybe we need an additional note saying "this is incorrect, won't be tested and will be rectified in later stages"?

2024-06-14 18:35 UTC, vic-ma commented on course-definition.yml
> +      abc
My thinking is that this sentence, which appears right before the tests section, should make it clear to readers that in this stage, you do not need to compress the body, therefore the body will remain uncompressed, and therefore you will see the uncompressed body in the tests:

> For this stage, you don't need to compress the body. You'll implement compression in a later stage.

So I don't think the reader will be confused by the tests having the uncompressed body.

But I also see where you're coming from, that we can de-emphasize the body by omitting it, so that the reader can focus in on the part that's actually being tested (the header).

I don't feel too strongly either way, so let's just go with omitting it.

2024-06-14 18:44 UTC, merged

2024-06-14 18:51 UTC, rohitpaulk commented on course-definition.yml
> +      abc
Sounds good! I do agree that either option _might not_ make a huge difference, it's hard to really tell without real user feedback. 

Based on user behaviour we've seen in the past - users tend to skim quite a bit, and it's hard to tell where something will feel off / catch their attention. That's why I tend to be really wary about any piece of information that looks "incorrect" (even though it might not be so after taking into account all the context in the instructions) - it _might_ cause confusion and distract from the task at hand.